# Site settings
title: UW Madison Directed Reading Program
email: drp-organizers@g-groups.wisc.edu
description: > # this means to ignore newlines until "baseurl:"
  
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://uwmadisondrp.github.io" # the base hostname & protocol for your site
production_url: "https://uwmadisondrp.github.io"
markdown: kramdown

sass:
  style: compressed

plugins:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
